name: Build Unity-iPhone Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build Unity-iPhone project
        run: |
          xcodebuild -project xcprojects/Unity-iPhone.xcodeproj -configuration Release -scheme Unity-iPhone -archivePath "Unity-iPhone.xcarchive"

      - name: Upload xcarchive as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Unity-iPhone.xcarchive
          path: Unity-iPhone.xcarchive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath "Unity-iPhone.xcarchive" -exportPath "Unity-iPhone.ipa"

      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Unity-iPhone.ipa
          path: Unity-iPhone.ipa
