name: Build Unity Project for iOS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Unity
        uses: actions/setup-unity@v1
        with:
          unity-version: '2022.3.47f1'  # Use the desired Unity version
          activate: true                 # Activate Unity license

      - name: Build Unity Project for iOS
        run: |
          cd UnityProject
          /Applications/Unity/Hub/Editor/2022.3.47f1/Unity.app/Contents/MacOS/Unity \
            -batchmode -quit -projectPath . \
            -executeMethod BuildScript.PerformBuild  # Ensure your build method matches this

      - name: Build Xcode Project
        run: |
          cd xcprojects
          xcodebuild -project Unity-iOS.xcodeproj \
                     -scheme MyUnityProject \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath ../MyUnityProject.xcarchive

      - name: Export IPA
        run: |
          cd xcprojects
          xcodebuild -exportArchive \
                     -archivePath ../MyUnityProject.xcarchive \
                     -exportPath ../MyUnityProject.ipa \
                     -exportOptionsPlist exportOptions.plist

      - name: Commit IPA
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add ../MyUnityProject.ipa
          git commit -m "Built IPA"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure the token is set in your repo secrets
