name: Build Unity Project for iOS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Unity
        uses: actions/setup-unity@v1
        with:
          unity-version: 2022.3.47f1
      - name: Build Unity Project for iOS
        run: |
          cd UnityProject
          ./Unity -batchmode -quit -projectPath . -executeMethod Build -buildTarget iOS -buildName MyUnityProject
      - name: Build Xcode Project
        run: |
          xcodebuild -project xcprojects/Unity-iOS.xcodeproj -scheme MyUnityProject -configuration Release -sdk iphoneos -archivePath MyUnityProject.xcarchive
      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath MyUnityProject.xcarchive -exportPath MyUnityProject.ipa -exportOptionsPlist exportOptions.plist
      - name: Commit IPA
        run: |
          git add MyUnityProject.ipa
          git commit -m "Built IPA"
          git push origin main
